### ISSUE TITLE
개발환경 세팅

### ISSUE THREAD

**Issue by pshpsh777** [pshpsh777/atti-api-server#1]
- [x] #3
- [x] #2

**Comment by yim0823** [comment]
#2 에 대한 환경 세팅이 마무리 된것으로 정리되어 있는데. 코드는 아무것도 없어서 설정 여부 마무리 된건가요?

**Comment by pshpsh777** [comment]
마스터 브랜치에 코드 올라가있지 않나요 ?! 
default 브랜치가 main 으로 되어있는데 master로 바꾸는 방법 혹시 아시나요 ~~

**Comment by pshpsh777** [comment]
오 라벨기능 좋은데여
