### ISSUE TITLE
spring-boot 환경세팅

### ISSUE THREAD

**Issue by pshpsh777** [pshpsh777/atti-api-server#2]

**Comment by pshpsh777** [comment]
# What is Spring-boot?
- Java 기반 Web Framework
- 기존에 많이 사용하던 Spring Framework의 복잡한 초기 환경설정을 간소화 시킨 버전
- starter library로 dependency에 존재하는 버전관리를 자동으로 해줌
- 톰캣같은 내장서버 존재

## Maven vs Gradle
- Maven: Java용 프로젝트 관리 툴
- Gradle: Java 외 언어 지원 (Python, C++)
- Gradle이 가독성이 더 좋고 성능도 더 빠름

# Start Spring-boot on IntelliJ
1. Create New Project (empty Project)
![image](https://user-images.githubusercontent.com/7835902/149500695-edc478cf-960e-4f12-85b3-b6790f2cb0d6.png)
![image](https://user-images.githubusercontent.com/7835902/149500732-ef0037f0-7365-467d-a506-eca696f405a9.png)
![image](https://user-images.githubusercontent.com/7835902/149500868-c01a018e-6bcd-48ce-9635-bb243bdba76d.png)
2. Add New Module in Project
![image](https://user-images.githubusercontent.com/7835902/149500961-dc11e85f-21f1-4c87-a4ef-e099953c72d0.png)
![image](https://user-images.githubusercontent.com/7835902/149501032-e804985b-b44b-4505-b095-85b5343bac30.png)
![image](https://user-images.githubusercontent.com/7835902/149501086-f6c5e91c-f4e7-46a3-8dc6-91811c369c34.png)
위 사진과 같이 Spring Initialize 항목이 있어야하는데 ....
![image](https://user-images.githubusercontent.com/7835902/149501231-11bd8154-5e13-40e5-af9a-e1370e753218.png)
없다!!!!
왜 없는지 찾아보니까.. Community 버전은 제공하지 않는다고 한다.. 흑 
https://start.spring.io/ 페이지의 프로젝트 생성기로 직접 생성해서 세팅해줘야한다
![image](https://user-images.githubusercontent.com/7835902/149501850-2140f83e-9af0-44a6-97b7-7dc83b7e7078.png)
- 원하는 프로젝트 유형 (gradle)
- 프로그래밍 언어 종류 (java)
- spring-boot 버전 (2.6.2)
- 프로젝트 메타데이터 (얘네가 의미하는건 뭐지..?)

**Comment by pshpsh777** [comment]
# Spring Initialize
![image](https://user-images.githubusercontent.com/7835902/149503726-cf3efee4-4fc8-41d4-b195-24f414462bed.png)

**Comment by pshpsh777** [comment]
# Jar vs War

**Comment by pshpsh777** [comment]
# Gradle

**Comment by pshpsh777** [comment]
# @SpringBootApplication
- 스프링부트의 가장 기본적인 설정을 세팅해준다.

# @ComponentScan

# @EnableAutoConfiguration

**Comment by yim0823** [comment]
개발 환경을 세팅한다고 하는 건데 이 참에 base-framework 을 만들어 보세요. 
필요한 라이브러리들 dependencies (gradle)에 추가하고 application.yaml 혹은 application.properties 에 라이브러리 관련한 설정들을 세팅해보세요. 
예를 들어, mariadb 설정을 하겠다라면, url, username, password, driver 를 세팅하 듯 이요.

**Comment by pshpsh777** [comment]
> 개발 환경을 세팅한다고 하는 건데 이 참에 base-framework 을 만들어 보세요. 필요한 라이브러리들 dependencies (gradle)에 추가하고 application.yaml 혹은 application.properties 에 라이브러리 관련한 설정들을 세팅해보세요. 예를 들어, mariadb 설정을 하겠다라면, url, username, password, driver 를 세팅하 듯 이요.

@
