### ISSUE TITLE
Rest APIs 명세서 작성

### ISSUE THREAD

**Issue by pshpsh777** [pshpsh777/atti-api-server#4]
crud url 추가

**Comment by yim0823** [comment]
rest api 룰에 따른 설계도 구글링해서 공부해보세요. 이미 아는 내용일꺼지만 도움될꺼에요

**Comment by pshpsh777** [comment]
# REST API 설계 Rules
REST : Representational State Transfer  (해석이 안됨..)
#### 정확한 의미가 뭔지 검색검색
- https://blog.npcode.com/2017/04/03/rest%EC%9D%98-representation%EC%9D%B4%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80/
- https://m.blog.naver.com/azure0777/221066646741

**Comment by yim0823** [comment]
해당 이슈 타이틀을 변경합니다. 
- 보다 디테일한 작업 단위로 이슈 타이틀 정리

해당 프로젝트의 APIs 명세서 작성 완료 후, close 진행 부탁드립니다.

**Comment by pshpsh777** [comment]
# 기능 명세
## 회원
1. 로그인
_전화번호, 패스워드_
2. 로그인 시 사용자와 관리자 권한에 따라 다르게 제공한다.

## 관리자
### 사용자 관리
1. 사용자 추가 
_전화번호, 패스워드, 이름, 나이, 주소, 등록날짜, 학교_
2. 사용자 수정
3. 사용자 삭제
4. 사용자 리스트 조회
5. 사용자 상세정보 조회 (by Id)
### 팀 관리
1. 팀 추가
_팀 이름, 수업요일, 수업시간_
2. 팀 삭제
3. 팀 조회
4. 팀 상세정보 조회
5. 팀 상세정보 수정
### 공지사항 관리
1. 공지사항 등록
_제목, 내용 , 타겟 팀_
2. 공지사항 수정
3. 공지사항 삭제
4. 공지사항 리스트 조회
5. 공지사항 상세정보 조회 (by Id)

## 사용자
### 공지사항 조회
1. 사용자가 속한 팀에 공지된 공지사항 리스트 확인
2. 공지사항 상세내용 확인

**Comment by yim0823** [comment]
기능 명세 토대로 Api 명세서 작성하면 되겠네요

**Comment by pshpsh777** [comment]
https://github.com/pshpsh777/atti-api-server/wiki/API-%EB%AA%85%EC%84%B8

Wiki 페이지에 API 명세 작성했습니다!
